#!/bin/bash

# pro-sub: demo of process substitution

while read attr links owner group size date time filename; do
  cat <<EOF
Filename:   $filename
Size:       $size
Owner:      $owner
Group:      $group
Modified:   $modified
Links:      $links
Attributes: $attributes
EOF
done < <(ls -l | tail -n +2)
