#!/bin/bash

# Script to retrieve a file fia FTP

FTP_SERVER=ftp.nl.debian.org
FTP_PATH=/debian/dists/wheezy/main/installer-i386/current/images/cdrom
REMOTE_FILE=debian-cd_info.tar.gz
echo $REMOTE_FILE
ftp -n <<- EOF
    open $FTP_SERVER
    user anonymous me@linuxbox
    cd $FTP_PATH
    hash
    get $REMOTE_FILE
    bye
EOF

ls -l $REMOTE_FILE

