#!/bin/bash

# while-menu: a menu driven system information program

DELAY=3 # Number of seconds to display results

while [[ $REPLY != 0 ]]; do
  clear
  cat <<EOF
Please Select:

A. Display System Information
B. Display Disk Space
C. Display Home Space Utilization
Q. Quit
EOF
  read -p "Enter selection [A-C or Q] > " 
  case $REPLY in
    q|Q)
      echo "Program terminated."
      exit
      ;;
    a|A)
      echo "Hostname: $HOSTNAME"
      uptime
      sleep $DELAY
      ;;
    b|B)
      df -h
      sleep $DELAY
      ;;
    c|C)
      if [[ $(id -u) -eq 0  ]]; then
        echo "Home Space Utilization (All Users)"
        du -sh /home/*
      else
        echo "Home Space Utilization ($USER)"
        du -sh $HOME
      fi
      sleep $DELAY
      ;;
    *)
      echo "Invalid entry" >&2
      exit 1
  esac
done

