#!/bin/bash

# Program to output a system information page

TITLE="System Information Report For $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIMESTAMP="Generated $CURRENT_TIME, by $USER"

function report_uptime() {
  cat<<EOF
<h2>System Uptime</h2>
<pre>$(uptime)</pre>
EOF
}


function report_disk_space() {
cat <<EOF
<h2>Disk Space Utilization</h2>
<pre>$(df -h)</pre>
EOF
}

function report_home_space() {
  if [ $(id -u) -eq 0 ]; then
    cat <<EOF
<h2>Home Space Utilization (All Users)</h2>
<pre>$(du -sh /home/*)</pre>
EOF
  else
    cat <<EOF
<h2>Home Space Utilization ($USER)</h2>
<pre>$(du -sh $HOME)</pre>
EOF
  fi
  return
}

Cat <<EOF  
<html>
   <head>
      <title>$TITLE</title>
   </head>
   <body>
      <h1>$TITLE</h1>
      <p>$TIMESTAMP</p>
      $(report_uptime)
      $(report_disk_space)
      $(report_home_space)
   </body>
EOF
