hacked-notesearch: hacked-notesearch.c
	gcc -o hacked-notesearch hacked-notesearch.c -g -fno-stack-protector -z execstack -m32


main-of: main-of.c
	gcc -o main-of main-of.c -g -fno-stack-protector -z execstack -m32

my-arpspoof: my-arpspoof.c
	gcc -o my-arpspoof my-arpspoof.c

syn-flooder: syn-flooder.c
	gcc -o syn-flooder syn-flooder.c
